# Generated by Django 4.2.1 on 2023-11-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_empresa_fecha_ultima_gestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('fecha_alerta', models.DateTimeField()),
                ('observacion', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_contacto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='tipo',
            field=models.CharField(choices=[('CO', 'Correo'), ('LL', 'Llamada'), ('VL', 'Videollamada'), ('RE', 'Reunion'), ('VI', 'Visita'), ('ME', 'Mensaje')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Anotacion',
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.empresa'),
        ),
    ]
